# Generated by Django 3.2.16 on 2022-11-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profstatus',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
