# Generated by Django 3.2.16 on 2022-11-18 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mr', '0003_employee_profstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_office', models.CharField(default='BLGF', max_length=10)),
                ('decription', models.CharField(max_length=100)),
                ('property_no', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=20)),
                ('year_acquired', models.CharField(max_length=5)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Original Value')),
                ('useful_life', models.IntegerField()),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salvage Value')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equips', to='mr.equipment')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propoff', to='mr.propertyofficer')),
                ('issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_tos', to='mr.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
